rule_name: Possible Changing Cor Profiler Environment Variable Powershell
id: 6544dc55621dda98eb93377d
description: Remove the Zone.Identifier alternate data stream which identifies the file as downloaded from the internet.
author: hieunc19
tags:
  - VCS_Content_Offline
  - Sprint_27
date: 2023/10/27
modified: 2023/10/27
product: VCS_CyM
status: experimental
mitre-attack:
  technique:
    - T1574.012
  datasource:
    - command.command_execution
    - script.script_execution
  tactic:
    - Persistence
    - Privilege Escalation
    - Defense Evasion
reference:
  - https://attack.mitre.org/techniques/T1574/012/
filter:
  event:
    logsource:
      log_parser: windows_event
      log_name: Microsoft-Windows-PowerShell/Operational 
      signature_id: 4104
    query:
      - AND:
        - sub_category|==: Execute a Remote Command
        - target_commandline|!=: null
        - target_commandline.replaceAll("\"|\'|","").toLowerCase()|assign|raw: $tcl
        - OR: 
          - $tcl|endswith: cor_profiler
          - $tcl|contains: cor_enable_profiling
        - OR:
          - $tcl|contains: "[environment]::setenvironmentvariable"
          - $tcl|contains: "$env:"
indicator:
  not_alert:
    query:
      - client_id|==|raw: $event.getClient_id()
    time_window: 1h
  accumulate:
    query:
      - client_id|==|raw: $event.getClient_id()
    time_window: 1h
    count|>=: 1 
  action:
    alert:
      alert_fields:
        object|raw: $event.getClient_id()
      event_fields:
        - log_parser
        - client_id
        - organization_group
        - source_name
        - log_name
        - signature_id
        - target_commandline
        - suser
        - hostname
        - user_name
        - customer_group
        - computer_name
        - file_path
severity: medium
version: 3
